---
AWSTemplateFormatVersion: '2010-09-09'
Description: Custom CloudFormation KMS Provider
Parameters:
  S3BucketPrefix:
    Type: String
    Default: 'binxio-public'
  CFNCustomProviderZipFileName:
    Type: String
    Default: lambdas/cfn-kms-provider-0.1.1.zip
Resources:
  CFNCustomProvider:
    Type: AWS::Lambda::Function
    DependsOn: LambdaPolicy
    Properties:
      Description: CloudFormation Custom:KMSGrant provider
      Code:
        S3Bucket: !Sub '${S3BucketPrefix}-${AWS::Region}'
        S3Key: !Ref 'CFNCustomProviderZipFileName'
      FunctionName: binxio-cfn-kms-grant-provider
      Handler: cfn_kms_provider.handler
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: python3.7

  LambdaPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - LambdaRole
    Properties:
      PolicyName: CFNKMSProvider
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'kms:CreateGrant'
              - 'kms:RetireGrant'
              - 'kms:RevokeGrant'
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:*
            Resource: arn:aws:logs:*:*:*
      Roles:
        - !Ref 'LambdaRole'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

  CFNCustomProviderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${CFNCustomProvider}'
      RetentionInDays: 7

